const pokedex = [
  {
    id: 1,
    name: "Bulbasaur",
    image: "/images/001.png",
    number: "001",
    type: "grass",
  },
  {
    id: 2,
    name: "Ivysaur",
    image: "/images/002.png",
    number: "002",
    type: "grass",
  },
  {
    id: 3,
    name: "Venusaur",
    image: "/images/003.png",
    number: "003",
    type: "grass",
  },
  {
    id: 4,
    name: "Charmander",
    image: "/images/004.png",
    number: "004",
    type: "fire",
  },
  {
    id: 5,
    name: "Charmeleon",
    image: "/images/005.png",
    number: "005",
    type: "fire",
  },
  {
    id: 6,
    name: "Charizard",
    image: "/images/006.png",
    number: "006",
    type: "fire",
  },
  {
    id: 7,
    name: "Squirtle",
    image: "/images/007.png",
    number: "007",
    type: "water",
  },
  {
    id: 8,
    name: "Wartortle",
    image: "/images/008.png",
    number: "008",
    type: "water",
  },
  {
    id: 9,
    name: "Blastoise",
    image: "/images/009.png",
    number: "009",
    type: "water",
  },
  {
    id: 10,
    name: "Caterpie",
    image: "/images/010.png",
    number: "010",
    type: "bug",
  },
  {
    id: 11,
    name: "Metapod",
    image: "/images/011.png",
    number: "011",
    type: "bug",
  },
  {
    id: 12,
    name: "Butterfree",
    image: "/images/012.png",
    number: "012",
    type: "bug",
  },
  {
    id: 13,
    name: "Weedle",
    image: "/images/013.png",
    number: "013",
    type: "bug",
  },
  {
    id: 14,
    name: "Kakuna",
    image: "/images/014.png",
    number: "014",
    type: "bug",
  },
  {
    id: 15,
    name: "Beedrill",
    image: "/images/015.png",
    number: "015",
    type: "bug",
  },
  {
    id: 16,
    name: "Pidgey",
    image: "/images/016.png",
    number: "016",
    type: "normal",
  },
  {
    id: 17,
    name: "Pidgeotto",
    image: "/images/017.png",
    number: "017",
    type: "normal",
  },
  {
    id: 18,
    name: "Pidgeot",
    image: "/images/018.png",
    number: "018",
    type: "normal",
  },
  {
    id: 19,
    name: "Rattata",
    image: "/images/019.png",
    number: "019",
    type: "normal",
  },
  {
    id: 20,
    name: "Raticate",
    image: "/images/020.png",
    number: "020",
    type: "normal",
  },
  {
    id: 21,
    name: "Spearow",
    image: "/images/021.png",
    number: "021",
    type: "normal",
  },
  {
    id: 22,
    name: "Fearow",
    image: "/images/022.png",
    number: "022",
    type: "normal",
  },
  {
    id: 23,
    name: "Ekans",
    image: "/images/023.png",
    number: "023",
    type: "poison",
  },
  {
    id: 24,
    name: "Arbok",
    image: "/images/024.png",
    number: "024",
    type: "poison",
  },
  {
    id: 25,
    name: "Pikachu",
    image: "/images/025.png",
    number: "025",
    type: "electric",
  },
  {
    id: 26,
    name: "Raichu",
    image: "/images/026.png",
    number: "026",
    type: "electric",
  },
  {
    id: 27,
    name: "Sandshrew",
    image: "/images/027.png",
    number: "027",
    type: "ground",
  },
  {
    id: 28,
    name: "Sandslash",
    image: "/images/028.png",
    number: "028",
    type: "ground",
  },
  {
    id: 29,
    name: "Nidoran",
    image: "/images/029.png",
    number: "029",
    type: "poison",
  },
  {
    id: 30,
    name: "Nidorina",
    image: "/images/030.png",
    number: "030",
    type: "poison",
  },
  {
    id: 31,
    name: "Nidoqueen",
    image: "/images/031.png",
    number: "031",
    type: "poison",
  },
  {
    id: 32,
    name: "Nidoran",
    image: "/images/032.png",
    number: "032",
    type: "poison",
  },
  {
    id: 33,
    name: "Nidorino",
    image: "/images/033.png",
    number: "033",
    type: "poison",
  },
  {
    id: 34,
    name: "Nidoking",
    image: "/images/034.png",
    number: "034",
    type: "poison",
  },
  {
    id: 35,
    name: "Clefairy",
    image: "/images/035.png",
    number: "035",
    type: "fairy",
  },
  {
    id: 36,
    name: "Clefable",
    image: "/images/036.png",
    number: "036",
    type: "fairy",
  },
  {
    id: 37,
    name: "Vulpix",
    image: "/images/037.png",
    number: "037",
    type: "fire",
  },
  {
    id: 38,
    name: "Ninetales",
    image: "/images/038.png",
    number: "038",
    type: "fire",
  },
  {
    id: 39,
    name: "Jigglypuff",
    image: "/images/039.png",
    number: "039",
    type: "fairy",
  },
];

export default pokedex;
